### PR TITLE
fix(ManifestAttributesChecker): jars must be relative to codebase

### LINKED ISSUE #256: JNLP resources can be relative to codebase
In the current implementation (master & 1.8 branch), the resources urls' paths must match exactly the codebase path, otherwise a warning dialog is displayed. This does not match Oracle's Web Start behavior, nor the JNLP specification (see rev9, 3.4: "An href element can either contain a relative URL or an absolute URL as shown above. A relative URL is relative to the URL given in the codebase attribute of the jnlp root element").

Created #258  pull request for 1.8 branch (missing ManifestAttributesCheckerTest because mocking would require too many classes, will be included with path for master)

### PR DESCRIPTION
**Pull request by SchwingSK**
Closes #256

I have created class DummySecurityDelegate as it seems that neither Mockito nor Easymock is used and I didn't want to introduce dependencies. Will happily do if required.

### CODE REVIEW

**Comment by hendrikebbers** [comment]
LGTM

File: core/src/main/java/net/sourceforge/jnlp/util/UrlUtils.java [hunk 1]
```diff
@@ -341,6 +315,45 @@ public static boolean urlEquals(final URL u1, final URL u2) {
...
+     * protocol://som.url/some/path/ is same as protocol://som.url/some/path. Even
+     * protocol://som.url/some/path\ is same as protocol://som.url/some/path/
+     *
+     * This method returns false in case <code>url</code> contains parent directory notation "..".
+     * See JNLP specification version 9, 3.4: 'A relative URL cannot contain parent directory notations, such as "..". It must denote a file that is stored in a subdirectory of the codebase.'
+     * @param url the url to check
+     * @param codebaseUrl the url to check against
+     * @return true if <code>url</code> is relative to <code>codebaseUrl</code>
+     */
+    public static boolean urlRelativeTo(URL url, URL codebaseUrl) {
```
Comment (hendrikebbers) [inline core/src/main/java/net/sourceforge/jnlp/util/UrlUtils.java]: pls add final to both parameters

File: core/src/main/java/net/sourceforge/jnlp/util/UrlUtils.java [hunk 2]
```diff
@@ -341,6 +315,45 @@ public static boolean urlEquals(final URL u1, final URL u2) {
...
+        if (codebaseUrl == url) {
+            return true;
+        }
+        if (codebaseUrl == null || url == null) {
+            return false;
+        }
+        try {
+            URL nu = sanitizeLastSlash(normalizeUrl(url));
```
Comment (hendrikebbers) [inline core/src/main/java/net/sourceforge/jnlp/util/UrlUtils.java]: pls make vars final

File: core/src/main/java/net/sourceforge/jnlp/util/UrlUtils.java [hunk 3]
```diff
@@ -341,6 +315,45 @@ public static boolean urlEquals(final URL u1, final URL u2) {
...
+            URL nup = sanitizeLastSlash(normalizeUrl(codebaseUrl));
+            if (!getHostAndPort(nu).equals(getHostAndPort(nup))) {
+                return false;
+            }
+            if (!nu.getProtocol().equals(nup.getProtocol())) {
+                return false;
+            }
+            if (nu.getPath().contains("..")) {
```
Comment (hendrikebbers) [inline core/src/main/java/net/sourceforge/jnlp/util/UrlUtils.java]: please define a constant

File: core/src/main/java/net/sourceforge/jnlp/util/UrlUtils.java [hunk 4]
```diff
@@ -341,6 +315,45 @@ public static boolean urlEquals(final URL u1, final URL u2) {
...
+                return false;
+            }
+            if (nu.getPath().startsWith(nup.getPath())) {
+                return true;
+            }
+        } catch (MalformedURLException | UnsupportedEncodingException | URISyntaxException e) {
+            LOG.error(IcedTeaWebConstants.DEFAULT_ERROR_MESSAGE, e);
```
Comment (hendrikebbers) [inline core/src/main/java/net/sourceforge/jnlp/util/UrlUtils.java]: Exception should be rethrown

Comment (sclassen) [reply core/src/main/java/net/sourceforge/jnlp/util/UrlUtils.java]: disagree on this. returning false is appropriate in this case.

Comment (hendrikebbers) [reply core/src/main/java/net/sourceforge/jnlp/util/UrlUtils.java]: @sclassen but the old implementation throws an exception.

Comment (hendrikebbers) [reply core/src/main/java/net/sourceforge/jnlp/util/UrlUtils.java]: In case of MalformedURLException

File: core/src/main/java/net/sourceforge/jnlp/util/UrlUtils.java (hunk 2 above)
Comment (sclassen) [reply core/src/main/java/net/sourceforge/jnlp/util/UrlUtils.java]: while you are at it, could you rename
- `nu` -> `sanUrl`
- `nup` -> `sanCodebase`

File: core/src/main/java/net/sourceforge/jnlp/util/UrlUtils.java (hunk 4 above)
Comment (sclassen) [reply core/src/main/java/net/sourceforge/jnlp/util/UrlUtils.java]: Yes, never the less I think the method should return false. If the URL is really malformed then it will trigger the `MalformedURLException` when ITW will try to download the resource. Which I find a better location to throw the exception.

File: core/src/main/java/net/sourceforge/jnlp/util/UrlUtils.java (hunk 1 above)
Comment (SchwingSK) [reply core/src/main/java/net/sourceforge/jnlp/util/UrlUtils.java]: Done.

File: core/src/main/java/net/sourceforge/jnlp/util/UrlUtils.java (hunk 3 above)
Comment (SchwingSK) [reply core/src/main/java/net/sourceforge/jnlp/util/UrlUtils.java]: Done.

File: core/src/main/java/net/sourceforge/jnlp/util/UrlUtils.java (hunk 2 above)
Comment (SchwingSK) [reply core/src/main/java/net/sourceforge/jnlp/util/UrlUtils.java]: Done.

File: core/src/main/java/net/sourceforge/jnlp/util/UrlUtils.java (hunk 4 above)
Comment (SchwingSK) [reply core/src/main/java/net/sourceforge/jnlp/util/UrlUtils.java]: I tend to side with @sclassen on this one, as MalformedURLException can be triggered by sanitizeLastSlash or normalizeUrl and in the current state these methods only throw MalformedURLException  because they use the URL constructor, but in effect it seems that they should never actually throw it as the constructed URL comes from an already valid URL (might be wrong on some edge cases in normalizeUrl method, I'm no expert).
That being said, I'll rethrow the exception if required :)
